services:
  - type: web
    name: bookhaven
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn bookstore.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
